version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - memcached
    networks:
      - app-network

  memcached:
    image: memcached:1.6-alpine
    ports:
      - "11211:11211"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge