version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jury-app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm rebuild bcrypt --build-from-source && npm run dev"
    depends_on:
      - memcached

  memcached:
    image: memcached:1.6-alpine
    container_name: jury-memcached
    ports:
      - "11211:11211"

networks:
  default:
    name: jury-network